grafana:
  enabled: true
  
  persistence:
    enabled: true
    type: pvc
    accessModes:
    - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection

  ingress:
    enabled: true
    annotations: {cert-manager.io/cluster-issuer: letsencrypt-prod}
    hosts: 
     - grafana.hossam.io
    tls: 
    - secretName: grafana-ingress-tls
      hosts:
       - grafana.hossam.io
    ingressClassName: kong
    paths: /
  
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"

    datasources:
      enabled: true
      defaultDatasourceEnabled: true


prometheus:
  ingress:
    enabled: true
    annotations: {cert-manager.io/cluster-issuer: letsencrypt-prod}
    hosts: 
     - prometheus.hossam.io
    tls: 
    - secretName: prometheus-ingress-tls
      hosts:
       - prometheus.hossam.io
    ingressClassName: kong
    paths:
      - /
      
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'bozo-book-info-service-micrometer'
        metrics_path: 'bookinfo/q/metrics' 
        honor_timestamps: true
        scrape_interval: 3s
        static_configs:
         - targets: ['book-info-service-svc.bozo-book-library-dev.svc.cluster.local:8080']
      - job_name: 'bozo-book-library-service-micrometer'
        metrics_path: 'booklib/q/metrics' 
        honor_timestamps: true
        scrape_interval: 3s
        static_configs:
         - targets: ['book-library-service-svc.bozo-book-library-dev.svc.cluster.local:8080']

additionalPrometheusRulesMap: 
  rule-name: 
    groups:
      - name: AllInstances
        rules: 
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          annotations:
            title: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          labels:
            application: 'bozobooks'
            source: 'prometheus'

        - alert: InstanceDown
          expr: up == 0
          for: 1m
          annotations:
            title: 'Instance {{ $labels.instance }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          labels:
            application: 'bozobooks'
            source: 'prometheus'


alertmanager:
  enabled: true
  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##

  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
        receiver: 'slack-notifications'
        repeat_interval: 1s
    receivers:
    - name: 'null'
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: "Alert: {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "Alert: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"